packages:
  - packages/*
  - playground
  - docs
catalog:
  '@antfu/install-pkg': ^1.1.0
  '@clack/prompts': ^0.10.1
  '@eslint/config-inspector': ^1.0.2
  '@eslint/js': ^9.26.0
  '@iconify-json/catppuccin': ^1.2.11
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.34
  '@nuxt/content': ^2.13.4
  '@nuxt/devtools': ^2.4.0
  '@nuxt/devtools-kit': ^2.4.0
  '@nuxt/fonts': ^0.11.3
  '@nuxt/image': ^1.10.0
  '@nuxt/kit': ^3.17.2
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.17.2
  '@nuxt/test-utils': ^3.18.0
  '@nuxt/ui-pro': ^1.8.0
  '@nuxthq/studio': ^2.2.1
  '@nuxtjs/eslint-config': ^12.0.0
  '@nuxtjs/plausible': ^1.2.0
  '@stylistic/eslint-plugin': ^4.2.0
  '@types/node': ^22.15.17
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  '@typescript-eslint/scope-manager': ^8.32.0
  '@typescript-eslint/types': ^8.32.0
  '@typescript-eslint/utils': ^8.32.0
  '@vueuse/core': ^13.1.0
  '@vueuse/nuxt': ^13.1.0
  bumpp: ^10.1.0
  chokidar: ^4.0.3
  eslint: ^9.26.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-standard: ^17.1.0
  eslint-flat-config-utils: ^2.0.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-import-x: ^4.11.1
  eslint-plugin-jsdoc: ^50.6.14
  eslint-plugin-n: ^17.18.0
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-vue: ^10.1.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.1.0
  eslint-webpack-plugin: ^5.0.1
  find-up: ^7.0.0
  get-port-please: ^3.1.2
  globals: ^16.1.0
  local-pkg: ^1.1.1
  mlly: ^1.7.4
  nuxt: ^3.17.2
  nuxt-og-image: ^5.1.3
  pathe: ^2.0.3
  taze: ^19.1.0
  typescript: ^5.8.3
  unimport: ^5.0.1
  vite-plugin-eslint2: ^5.0.3
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-eslint-parser: ^10.1.3
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
