packages:
  - packages/*
  - playground
  - docs

catalogs:
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint/config-inspector': ^1.3.0
    '@eslint/js': ^9.38.0
    '@nuxt/devtools-kit': ^3.0.0
    '@nuxt/kit': ^4.2.1
    '@stylistic/eslint-plugin': ^5.5.0
    '@typescript-eslint/eslint-plugin': ^8.46.2
    '@typescript-eslint/parser': ^8.46.2
    '@typescript-eslint/scope-manager': ^8.46.2
    '@typescript-eslint/types': ^8.46.2
    '@typescript-eslint/utils': ^8.46.2
    chokidar: ^4.0.3
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-format: ^1.0.2
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsdoc: ^61.1.10
    eslint-plugin-n: ^17.23.1
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-vue: ^10.5.1
    eslint-processor-vue-blocks: ^2.0.0
    eslint-typegen: ^2.3.0
    eslint-webpack-plugin: ^5.0.2
    find-up: ^8.0.0
    get-port-please: ^3.2.0
    globals: ^16.4.0
    local-pkg: ^1.1.2
    mlly: ^1.8.0
    pathe: ^2.0.3
    unimport: ^5.5.0
    vite-plugin-eslint2: ^5.0.4
    vue-eslint-parser: ^10.2.0
    vue: ^3.5.22
  bundling:
    '@nuxt/module-builder': ^1.0.2
  docs:
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/simple-icons': ^1.2.56
    '@nuxt/content': ^3.7.1
    '@nuxt/devtools': ^3.0.0
    '@nuxt/fonts': ^0.11.4
    '@nuxt/image': ^1.11.0
    '@nuxt/test-utils': ^3.20.1
    '@nuxt/ui-pro': ^3.3.7
    '@nuxthq/studio': ^2.2.1
    '@nuxtjs/plausible': ^2.0.1
    '@vueuse/core': ^14.0.0
    '@vueuse/nuxt': ^14.0.0
    nuxt-og-image: ^5.1.12
  types:
    '@types/node': ^24.9.2
    '@nuxt/schema': ^4.2.1
  dev:
    bumpp: ^10.3.1
    eslint-plugin-pnpm: ^1.3.0
    eslint: ^9.38.0
    jsonc-eslint-parser: ^2.4.1
    nuxt: ^4.2.1
    taze: ^19.8.1
    typescript: ^5.9.3
    vitest: ^4.0.4

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
