packages:
  - packages/*
  - packages-legacy/*
  - playground
  - docs
catalog:
  '@antfu/install-pkg': ^0.5.0
  '@clack/prompts': ^0.9.0
  '@eslint/config-inspector': ^0.6.0
  '@eslint/js': ^9.16.0
  '@iconify-json/catppuccin': ^1.2.8
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.16
  '@nuxt/content': ^2.13.4
  '@nuxt/devtools': 1.3.1
  '@nuxt/devtools-kit': ^1.6.4
  '@nuxt/fonts': ^0.10.3
  '@nuxt/image': ^1.8.1
  '@nuxt/kit': ^3.14.1592
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.14.1592
  '@nuxt/test-utils': ^3.15.1
  '@nuxt/ui-pro': ^1.6.0
  '@nuxthq/studio': ^2.2.1
  '@nuxtjs/eslint-config': ^12.0.0
  '@nuxtjs/plausible': ^1.2.0
  '@stylistic/eslint-plugin': ^2.12.1
  '@types/node': ^22.10.2
  '@typescript-eslint/eslint-plugin': ^8.18.1
  '@typescript-eslint/parser': ^8.18.1
  '@typescript-eslint/scope-manager': ^8.18.1
  '@typescript-eslint/types': ^8.18.1
  '@typescript-eslint/utils': ^8.18.1
  '@vueuse/core': ^12.0.0
  '@vueuse/nuxt': ^12.0.0
  bumpp: ^9.9.1
  chokidar: ^4.0.3
  eslint: ^9.17.0
  eslint-config-flat-gitignore: 0.2.0
  eslint-config-standard: ^17.1.0
  eslint-flat-config-utils: ^0.4.0
  eslint-import-resolver-typescript: ^3.7.0
  eslint-merge-processors: ^0.1.0
  eslint-plugin-format: ^0.1.3
  eslint-plugin-import: ^2.31.0
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-jsdoc: ^50.6.1
  eslint-plugin-n: ^17.15.0
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-vue: ^9.32.0
  eslint-processor-vue-blocks: ^0.1.2
  eslint-typegen: ^0.3.2
  eslint-webpack-plugin: ^4.2.0
  fast-glob: ^3.3.2
  find-up: ^7.0.0
  get-port-please: ^3.1.2
  globals: ^15.14.0
  local-pkg: ^0.5.1
  mlly: ^1.7.3
  nuxt: ^3.14.1592
  nuxt-og-image: ^4.0.1
  pathe: ^1.1.2
  taze: ^0.18.0
  typescript: ^5.7.2
  unimport: ^3.14.5
  vite-plugin-eslint2: ^5.0.3
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
