packages:
  - packages/*
  - playground
  - docs
catalog:
  '@antfu/install-pkg': ^1.0.0
  '@clack/prompts': ^0.10.0
  '@eslint/config-inspector': ^1.0.2
  '@eslint/js': ^9.23.0
  '@iconify-json/catppuccin': ^1.2.10
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.29
  '@nuxt/content': ^2.13.4
  '@nuxt/devtools': ^2.3.2
  '@nuxt/devtools-kit': ^2.3.2
  '@nuxt/fonts': ^0.11.0
  '@nuxt/image': ^1.10.0
  '@nuxt/kit': ^3.16.1
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.16.1
  '@nuxt/test-utils': ^3.17.2
  '@nuxt/ui-pro': ^1.7.1
  '@nuxthq/studio': ^2.2.1
  '@nuxtjs/eslint-config': ^12.0.0
  '@nuxtjs/plausible': ^1.2.0
  '@stylistic/eslint-plugin': ^4.2.0
  '@types/node': ^22.13.14
  '@typescript-eslint/eslint-plugin': ^8.28.0
  '@typescript-eslint/parser': ^8.28.0
  '@typescript-eslint/scope-manager': ^8.28.0
  '@typescript-eslint/types': ^8.28.0
  '@typescript-eslint/utils': ^8.28.0
  '@vueuse/core': ^13.0.0
  '@vueuse/nuxt': ^13.0.0
  bumpp: ^10.1.0
  chokidar: ^4.0.3
  eslint: ^9.23.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-standard: ^17.1.0
  eslint-flat-config-utils: ^2.0.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-import-x: ^4.9.4
  eslint-plugin-jsdoc: ^50.6.9
  eslint-plugin-n: ^17.17.0
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^58.0.0
  eslint-plugin-vue: ^10.0.0
  eslint-processor-vue-blocks: ^2.0.0
  eslint-typegen: ^2.1.0
  eslint-webpack-plugin: ^5.0.0
  find-up: ^7.0.0
  get-port-please: ^3.1.2
  globals: ^16.0.0
  local-pkg: ^1.1.1
  mlly: ^1.7.4
  nuxt: ^3.16.1
  nuxt-og-image: ^5.1.1
  pathe: ^2.0.3
  taze: ^19.0.4
  typescript: ^5.8.2
  unimport: ^5.0.1
  vite-plugin-eslint2: ^5.0.3
  vitest: ^3.0.9
  vue: ^3.5.13
  vue-eslint-parser: ^10.1.1
onlyBuiltDependencies:
  - esbuild
  - vue-demi
