packages:
  - packages/*
  - playground
  - docs
catalog:
  '@antfu/install-pkg': ^1.0.0
  '@clack/prompts': ^0.9.1
  '@eslint/config-inspector': ^1.0.0
  '@eslint/js': ^9.19.0
  '@iconify-json/catppuccin': ^1.2.8
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.23
  '@nuxt/content': ^2.13.4
  '@nuxt/devtools': ^1.7.0
  '@nuxt/devtools-kit': ^1.7.0
  '@nuxt/fonts': ^0.10.3
  '@nuxt/image': ^1.9.0
  '@nuxt/kit': ^3.15.4
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.15.4
  '@nuxt/test-utils': ^3.15.4
  '@nuxt/ui-pro': ^1.7.0
  '@nuxthq/studio': ^2.2.1
  '@nuxtjs/eslint-config': ^12.0.0
  '@nuxtjs/plausible': ^1.2.0
  '@stylistic/eslint-plugin': ^3.0.1
  '@types/node': ^22.13.1
  '@typescript-eslint/eslint-plugin': ^8.23.0
  '@typescript-eslint/parser': ^8.23.0
  '@typescript-eslint/scope-manager': ^8.23.0
  '@typescript-eslint/types': ^8.23.0
  '@typescript-eslint/utils': ^8.23.0
  '@vueuse/core': ^12.5.0
  '@vueuse/nuxt': ^12.5.0
  bumpp: ^10.0.2
  chokidar: ^4.0.3
  eslint: ^9.19.0
  eslint-config-flat-gitignore: ^2.0.0
  eslint-config-standard: ^17.1.0
  eslint-flat-config-utils: ^2.0.1
  eslint-import-resolver-typescript: ^3.7.0
  eslint-merge-processors: ^1.0.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-import: ^2.31.0
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-jsdoc: ^50.6.3
  eslint-plugin-n: ^17.15.1
  eslint-plugin-promise: ^7.2.1
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-vue: ^9.32.0
  eslint-processor-vue-blocks: ^1.0.0
  eslint-typegen: ^1.0.0
  eslint-webpack-plugin: ^4.2.0
  fast-glob: ^3.3.3
  find-up: ^7.0.0
  get-port-please: ^3.1.2
  globals: ^15.14.0
  local-pkg: ^1.0.0
  mlly: ^1.7.4
  nuxt: ^3.15.4
  nuxt-og-image: ^4.1.2
  pathe: ^2.0.2
  taze: ^18.4.0
  typescript: ^5.7.3
  unimport: ^4.1.0
  vite-plugin-eslint2: ^5.0.3
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
