packages:
  - packages/*
  - packages-legacy/*
  - playground
  - docs
catalog:
  '@eslint/config-inspector': ^0.5.5
  '@eslint/js': ^9.13.0
  '@iconify-json/catppuccin': ^1.2.4
  '@iconify-json/ph': ^1.2.1
  '@iconify-json/simple-icons': ^1.2.9
  '@nuxt/content': ^2.13.4
  '@nuxt/devtools': 1.3.1
  '@nuxt/devtools-kit': ^1.6.0
  '@nuxt/fonts': ^0.10.2
  '@nuxt/image': ^1.8.1
  '@nuxt/kit': ^3.13.2
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.13.2
  '@nuxt/test-utils': ^3.14.4
  '@nuxt/ui-pro': ^1.4.4
  '@nuxthq/studio': ^2.1.1
  '@nuxtjs/eslint-config': ^12.0.0
  '@nuxtjs/plausible': ^1.0.3
  '@stylistic/eslint-plugin': ^2.9.0
  '@types/node': ^22.7.9
  '@typescript-eslint/eslint-plugin': ^8.11.0
  '@typescript-eslint/parser': ^8.11.0
  '@typescript-eslint/scope-manager': ^8.11.0
  '@typescript-eslint/types': ^8.11.0
  '@typescript-eslint/utils': ^8.11.0
  '@vueuse/core': ^11.1.0
  '@vueuse/nuxt': ^11.1.0
  bumpp: ^9.7.1
  chokidar: ^4.0.1
  eslint: ^9.13.0
  eslint-config-flat-gitignore: ^0.3.0
  eslint-config-standard: ^17.1.0
  eslint-flat-config-utils: ^0.4.0
  eslint-import-resolver-typescript: ^3.6.3
  eslint-plugin-import: ^2.31.0
  eslint-plugin-import-x: ^4.3.1
  eslint-plugin-jsdoc: ^50.4.3
  eslint-plugin-n: ^17.11.1
  eslint-plugin-promise: ^7.1.0
  eslint-plugin-regexp: ^2.6.0
  eslint-plugin-unicorn: ^56.0.0
  eslint-plugin-vue: ^9.29.1
  eslint-typegen: ^0.3.2
  eslint-webpack-plugin: ^4.2.0
  fast-glob: ^3.3.2
  find-up: ^7.0.0
  get-port-please: ^3.1.2
  globals: ^15.11.0
  local-pkg: ^0.5.0
  mlly: ^1.7.2
  nuxt: ^3.13.2
  nuxt-og-image: ^3.0.6
  pathe: ^1.1.2
  taze: ^0.17.2
  typescript: ^5.6.3
  unimport: ^3.13.1
  vite-plugin-eslint2: ^5.0.1
  vitest: ^2.1.3
  vue: ^3.5.12
  vue-eslint-parser: ^9.4.3
