packages:
  - packages/*
  - playground
  - docs

catalogs:
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.10.1
    '@eslint/config-inspector': ^1.0.2
    '@eslint/js': ^9.27.0
    '@nuxt/devtools-kit': ^2.4.1
    '@nuxt/kit': ^3.17.6
    '@stylistic/eslint-plugin': ^4.2.0
    '@typescript-eslint/eslint-plugin': ^8.32.1
    '@typescript-eslint/parser': ^8.32.1
    '@typescript-eslint/scope-manager': ^8.32.1
    '@typescript-eslint/types': ^8.32.1
    '@typescript-eslint/utils': ^8.32.1
    chokidar: ^4.0.3
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.0.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-import-x: ^4.12.2
    eslint-plugin-jsdoc: ^50.6.17
    eslint-plugin-n: ^17.18.0
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-regexp: ^2.7.0
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-vue: ^10.1.0
    eslint-processor-vue-blocks: ^2.0.0
    eslint-typegen: ^2.2.0
    eslint-webpack-plugin: ^5.0.1
    find-up: ^7.0.0
    get-port-please: ^3.1.2
    globals: ^16.1.0
    local-pkg: ^1.1.1
    mlly: ^1.7.4
    pathe: ^2.0.3
    unimport: ^5.0.1
    vite-plugin-eslint2: ^5.0.3
    vue-eslint-parser: ^10.1.3
    vue: ^3.5.14

  bundling:
    '@nuxt/module-builder': ^1.0.1

  docs:
    '@iconify-json/catppuccin': ^1.2.11
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/simple-icons': ^1.2.34
    '@nuxt/content': ^2.13.4
    '@nuxt/devtools': ^2.4.1
    '@nuxt/fonts': ^0.11.4
    '@nuxt/image': ^1.10.0
    '@nuxt/test-utils': ^3.19.0
    '@nuxt/ui-pro': ^1.8.0
    '@nuxthq/studio': ^2.2.1
    '@nuxtjs/plausible': ^1.2.0
    '@vueuse/core': ^13.2.0
    '@vueuse/nuxt': ^13.2.0
    nuxt-og-image: ^5.1.3

  types:
    '@types/node': ^22.15.19
    '@nuxt/schema': ^3.17.6

  dev:
    bumpp: ^10.1.1
    eslint-plugin-pnpm: ^0.3.1
    eslint: ^9.27.0
    jsonc-eslint-parser: ^2.4.0
    nuxt: ^3.17.6
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.1.4

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
