name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
    paths-ignore:
      - "docs/**"

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Test (unit)
        run: pnpm test -u

      - name: Lint (code)
        run: pnpm lint:fix

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
